apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  db-username: YXBwX3VzZXI=       # base64 encoded value of 'app_user'
  db-password: c2VjdXJlX3Bhc3N3b3Jk # base64 encoded value of 'secure_password'
