-- Create table for user data
CREATE TABLE IF NOT EXISTS DimUser (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(150) NOT NULL,
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    email VARCHAR(254),
    is_active BOOLEAN DEFAULT TRUE,
    is_staff BOOLEAN DEFAULT FALSE,
    is_superuser BOOLEAN DEFAULT FALSE,
    date_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- Insert sample data into DimUser table
-- Insert statements for DimUser table

INSERT INTO DimUser (username, first_name, last_name, email, is_active, is_staff, is_superuser) VALUES
('user1', 'John', 'Doe', 'john.doe1@example.com', TRUE, FALSE, FALSE),
('user2', 'Jane', 'Smith', 'jane.smith2@example.com', TRUE, TRUE, FALSE),
('user3', 'Alice', 'Johnson', 'alice.johnson3@example.com', TRUE, FALSE, FALSE),
('user4', 'Bob', 'Brown', 'bob.brown4@example.com', TRUE, FALSE, TRUE),
('user5', 'Charlie', 'Davis', 'charlie.davis5@example.com', TRUE, TRUE, FALSE),
('user6', 'David', 'Miller', 'david.miller6@example.com', TRUE, FALSE, FALSE),
('user7', 'Eve', 'Wilson', 'eve.wilson7@example.com', TRUE, TRUE, TRUE),
('user8', 'Frank', 'Moore', 'frank.moore8@example.com', TRUE, FALSE, FALSE),
('user9', 'Grace', 'Taylor', 'grace.taylor9@example.com', TRUE, TRUE, FALSE),
('user10', 'Hank', 'Anderson', 'hank.anderson10@example.com', TRUE, FALSE, TRUE),
('user11', 'Ivy', 'Thomas', 'ivy.thomas11@example.com', TRUE, TRUE, FALSE),
('user12', 'Jack', 'Jackson', 'jack.jackson12@example.com', TRUE, FALSE, FALSE),
('user13', 'Kara', 'White', 'kara.white13@example.com', TRUE, TRUE, TRUE),
('user14', 'Leo', 'Harris', 'leo.harris14@example.com', TRUE, FALSE, FALSE),
('user15', 'Mona', 'Martin', 'mona.martin15@example.com', TRUE, TRUE, FALSE),
('user16', 'Nina', 'Lee', 'nina.lee16@example.com', TRUE, FALSE, FALSE),
('user17', 'Oscar', 'Garcia', 'oscar.garcia17@example.com', TRUE, TRUE, TRUE),
('user18', 'Paul', 'Rodriguez', 'paul.rodriguez18@example.com', TRUE, FALSE, TRUE),
('user19', 'Quincy', 'Martinez', 'quincy.martinez19@example.com', TRUE, TRUE, FALSE),
('user20', 'Rachel', 'Hernandez', 'rachel.hernandez20@example.com', TRUE, FALSE, FALSE),
('user21', 'Sam', 'Young', 'sam.young21@example.com', TRUE, TRUE, FALSE),
('user22', 'Tom', 'King', 'tom.king22@example.com', TRUE, FALSE, TRUE),
('user23', 'Uma', 'Scott', 'uma.scott23@example.com', TRUE, TRUE, FALSE),
('user24', 'Vera', 'Adams', 'vera.adams24@example.com', TRUE, FALSE, FALSE),
('user25', 'Will', 'Baker', 'will.baker25@example.com', TRUE, TRUE, TRUE),
('user26', 'Xander', 'Gonzalez', 'xander.gonzalez26@example.com', TRUE, FALSE, FALSE),
('user27', 'Yara', 'Nelson', 'yara.nelson27@example.com', TRUE, TRUE, FALSE),
('user28', 'Zane', 'Carter', 'zane.carter28@example.com', TRUE, FALSE, TRUE),
('user29', 'Aaron', 'Mitchell', 'aaron.mitchell29@example.com', TRUE, TRUE, TRUE),
('user30', 'Beth', 'Perez', 'beth.perez30@example.com', TRUE, FALSE, FALSE),
('user31', 'Cathy', 'Roberts', 'cathy.roberts31@example.com', TRUE, TRUE, FALSE),
('user32', 'Dylan', 'Evans', 'dylan.evans32@example.com', TRUE, FALSE, TRUE),
('user33', 'Ella', 'Green', 'ella.green33@example.com', TRUE, TRUE, FALSE),
('user34', 'Finn', 'Hall', 'finn.hall34@example.com', TRUE, FALSE, FALSE),
('user35', 'Gina', 'Young', 'gina.young35@example.com', TRUE, TRUE, TRUE),
('user36', 'Holly', 'Bennett', 'holly.bennett36@example.com', TRUE, FALSE, FALSE),
('user37', 'Ian', 'Cameron', 'ian.cameron37@example.com', TRUE, TRUE, FALSE),
('user38', 'Jade', 'Parker', 'jade.parker38@example.com', TRUE, FALSE, TRUE),
('user39', 'Karl', 'Evans', 'karl.evans39@example.com', TRUE, TRUE, FALSE),
('user40', 'Lily', 'Flores', 'lily.flores40@example.com', TRUE, FALSE, FALSE),
('user41', 'Max', 'Gomez', 'max.gomez41@example.com', TRUE, TRUE, TRUE),
('user42', 'Nina', 'Sanchez', 'nina.sanchez42@example.com', TRUE, FALSE, FALSE),
('user43', 'Oscar', 'Garcia', 'oscar.garcia43@example.com', TRUE, TRUE, FALSE),
('user44', 'Penny', 'Brown', 'penny.brown44@example.com', TRUE, FALSE, TRUE),
('user45', 'Quinn', 'Davis', 'quinn.davis45@example.com', TRUE, TRUE, TRUE),
('user46', 'Rachel', 'Miller', 'rachel.miller46@example.com', TRUE, FALSE, FALSE),
('user47', 'Steve', 'Roberts', 'steve.roberts47@example.com', TRUE, TRUE, FALSE),
('user48', 'Tina', 'Watson', 'tina.watson48@example.com', TRUE, FALSE, TRUE),
('user49', 'Ursula', 'Collins', 'ursula.collins49@example.com', TRUE, TRUE, FALSE),
('user50', 'Victor', 'Baker', 'victor.baker50@example.com', TRUE, FALSE, FALSE),
('user51', 'Wendy', 'Cameron', 'wendy.cameron51@example.com', TRUE, TRUE, TRUE),
('user52', 'Xena', 'King', 'xena.king52@example.com', TRUE, FALSE, TRUE),
('user53', 'Yolanda', 'Green', 'yolanda.green53@example.com', TRUE, TRUE, FALSE),
('user54', 'Zoe', 'Nelson', 'zoe.nelson54@example.com', TRUE, FALSE, TRUE),
('user55', 'Aaron', 'Rodriguez', 'aaron.rodriguez55@example.com', TRUE, TRUE, TRUE),
('user56', 'Beth', 'Lopez', 'beth.lopez56@example.com', TRUE, FALSE, FALSE),
('user57', 'Cynthia', 'Martinez', 'cynthia.martinez57@example.com', TRUE, TRUE, FALSE),
('user58', 'David', 'Moore', 'david.moore58@example.com', TRUE, FALSE, TRUE),
('user59', 'Emily', 'Harris', 'emily.harris59@example.com', TRUE, TRUE, FALSE),
('user60', 'Frank', 'Gonzalez', 'frank.gonzalez60@example.com', TRUE, FALSE, TRUE),
('user61', 'Grace', 'Morris', 'grace.morris61@example.com', TRUE, TRUE, FALSE),
('user62', 'Hank', 'Roberts', 'hank.roberts62@example.com', TRUE, FALSE, TRUE),
('user63', 'Iris', 'Walker', 'iris.walker63@example.com', TRUE, TRUE, FALSE),
('user64', 'Jack', 'Allen', 'jack.allen64@example.com', TRUE, FALSE, TRUE),
('user65', 'Kara', 'Scott', 'kara.scott65@example.com', TRUE, TRUE, TRUE),
('user66', 'Leo', 'Clark', 'leo.clark66@example.com', TRUE, FALSE, FALSE),
('user67', 'Maya', 'Walker', 'maya.walker67@example.com', TRUE, TRUE, FALSE),
('user68', 'Nathan', 'Adams', 'nathan.adams68@example.com', TRUE, FALSE, TRUE),
('user69', 'Olivia', 'Martinez', 'olivia.martinez69@example.com', TRUE, TRUE, FALSE),
('user70', 'Paul', 'Garcia', 'paul.garcia70@example.com', TRUE, FALSE, TRUE),
('user71', 'Quincy', 'White', 'quincy.white71@example.com', TRUE, TRUE, TRUE),
('user72', 'Rachel', 'Miller', 'rachel.miller72@example.com', TRUE, FALSE, FALSE),
('user73', 'Sam', 'Davis', 'sam.davis73@example.com', TRUE, TRUE, FALSE),
('user74', 'Tina', 'Moore', 'tina.moore74@example.com', TRUE, FALSE, TRUE),
('user75', 'Ursula', 'Wilson', 'ursula.wilson75@example.com', TRUE, TRUE, FALSE),
('user76', 'Victor', 'Roberts', 'victor.roberts76@example.com', TRUE, FALSE, TRUE),
('user77', 'Wendy', 'Baker', 'wendy.baker77@example.com', TRUE, TRUE, FALSE),
('user78', 'Xander', 'Martinez', 'xander.martinez78@example.com', TRUE, FALSE, TRUE),
('user79', 'Yvonne', 'Morris', 'yvonne.morris79@example.com', TRUE, TRUE, FALSE),
('user80', 'Zach', 'Allen', 'zach.allen80@example.com', TRUE, FALSE, TRUE),
('user81', 'Amos', 'Wilson', 'amos.wilson81@example.com', TRUE, TRUE, FALSE),
('user82', 'Blanca', 'Taylor', 'blanca.taylor82@example.com', TRUE, FALSE, TRUE),
('user83', 'Carlos', 'Harris', 'carlos.harris83@example.com', TRUE, TRUE, FALSE),
('user84', 'Diana', 'Scott', 'diana.scott84@example.com', TRUE, FALSE, TRUE),
('user85', 'Eric', 'Lee', 'eric.lee85@example.com', TRUE, TRUE, TRUE),
('user86', 'Frances', 'Cameron', 'frances.cameron86@example.com', TRUE, FALSE, FALSE),
('user87', 'George', 'Clark', 'george.clark87@example.com', TRUE, TRUE, FALSE),
('user88', 'Helen', 'Adams', 'helen.adams88@example.com', TRUE, FALSE, TRUE),
('user89', 'Ivy', 'Gonzalez', 'ivy.gonzalez89@example.com', TRUE, TRUE, FALSE),
('user90', 'Jack', 'Nelson', 'jack.nelson90@example.com', TRUE, FALSE, TRUE),
('user91', 'Kathy', 'Baker', 'kathy.baker91@example.com', TRUE, TRUE, FALSE),
('user92', 'Leo', 'Miller', 'leo.miller92@example.com', TRUE, FALSE, TRUE),
('user93', 'Monica', 'White', 'monica.white93@example.com', TRUE, TRUE, FALSE),
('user94', 'Nina', 'Adams', 'nina.adams94@example.com', TRUE, FALSE, TRUE),
('user95', 'Oscar', 'Taylor', 'oscar.taylor95@example.com', TRUE, TRUE, FALSE),
('user96', 'Paul', 'Clark', 'paul.clark96@example.com', TRUE, FALSE, TRUE),
('user97', 'Quinn', 'Walker', 'quinn.walker97@example.com', TRUE, TRUE, FALSE),
('user98', 'Rachel', 'Gonzalez', 'rachel.gonzalez98@example.com', TRUE, FALSE, TRUE),
('user99', 'Stan', 'Harris', 'stan.harris99@example.com', TRUE, TRUE, FALSE),
('user100', 'Tina', 'Nelson', 'tina.nelson100@example.com', TRUE, FALSE, TRUE);
